repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts



releases:
  - name: argocd
    namespace: argocd
    chart: ./argocd
    version: "0.1.1"
    wait: true
    installed: true
  - name: prom-norbac-ubuntu
    namespace: prometheus
    chart: prometheus-community/prometheus
    set:
    - name: rbac.create
      value: false